<?php/*** @author Thomas Allam / Romain Semler** @file Image.php** @date 25/02/2016** @brief Classe en charge des informations et des commentaires d'une image.*/
	class Image {

		public $bdd;

		function __construct($bdd) {
			$this->bdd = $bdd;
		}
		public function newImage($lien, $titre, $description, $theme, $confidentialite, $id) {			$req_insert = $this->bdd->prepare('INSERT INTO images (lien_img, titre_img, description_img, theme_img, is_public_img, nombre_aime_img, date_upload_img, suppression_img, id_user) VALUES(:lien, :titre, :description, :theme, :confidentialite, 0, NOW(), 0, :id)');			$req_insert->execute(array('lien' => $lien, 'titre' => $titre, 'description' => $description, 'theme' => $theme, 'confidentialite' => $confidentialite, 'id' => $id));			$req_insert->closeCursor();			$req_id = $this->bdd->prepare('SELECT id_img FROM images WHERE lien_img = :lien');			$req_id->execute(array('lien' => $lien));			$id_new_image = $req_id->fetch();			$req_id->closeCursor();			return $id_new_image;		}		public function getImage($id_img) {			$req_img = $this->bdd->prepare('SELECT * FROM images WHERE id_img = :img');			$req_img->execute(array('img' => $id_img));			$info_img = $req_img->fetch();			$req_img->closeCursor();			return $info_img;		}		
		public function getComImage($id_img) {
			$req_com = $this->bdd->prepare('SELECT * FROM commentaire WHERE id_img = :img');			$req_com->execute(array('img' => $id_img));
			$comment = $req_com->fetch();
			$req_com->closeCursor();			
			return $comment;
		}				public function getAllUserImages($id_user) {			$req_all_img = $this->bdd->prepare('SELECT id_img FROM images WHERE id_user = :id');			$req_all_img->execute(array('id' => $id_user));			$id_img = $req_all_img->fetchAll();			$req_all_img->closeCursor();						return $id_img;		}				public function getAllImages() {			$req_all_img = $this->bdd->prepare('SELECT id_img, lien_img, titre_img, description_img, theme_img, is_public_img, nombre_aime_img, DATE_FORMAT(date_upload_img, \'%d / %m / %Y\') AS date_upload_img, suppression_img, id_user FROM images ORDER BY id_img DESC');			$req_all_img->execute();			$data_img = $req_all_img->fetchAll();			$req_all_img->closeCursor();						return $data_img;		}				public function deleteImage($id_img) {						$get_lien = $this->bdd->prepare('SELECT lien_img FROM images WHERE id_img = :id');			$get_lien->execute(array('id' => $id_img));			$lien = $get_lien->fetch();			$get_lien->closeCursor();						$req_del = $this->bdd->prepare('DELETE FROM images WHERE id_img = :id');			$req_del_link = $this->bdd->prepare('DELETE FROM posseder_image WHERE id_img = :id');						$req_del->execute(array('id' => $id_img));			$req_del_link->execute(array('id' => $id_img));						$req_del->closeCursor();			$req_del_link->closeCursor();						unlink('../../' . $lien['lien_img']);						return true;		}				public function deleteUserImages($id_user) {					$all_id = $this->getAllUserImages($id_user);						foreach ($all_id as $id => $valeur) {							$this->deleteImage($valeur['id_img']);			}						return true;		}	}?>